# Generated by Django 5.1.2 on 2024-11-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_groups_user_is_active_user_is_admin_and_more'),
    ]

    operations = [
    ]
