# Generated by Django 4.2.5 on 2024-11-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20241103_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/photos/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_process', 'In Process'), ('sent', 'Sent'), ('delivered', 'Delivered')], default='in_process', max_length=20),
        ),
    ]
