# Generated by Django 5.1.2 on 2024-11-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_user_options_remove_user_is_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("pix", "Pix"), ("cash_on_delivery", "Cash on Delivery")],
                default="cash_on_delivery",
                max_length=20,
            ),
        ),
    ]
