# Generated by Django 4.2.5 on 2024-11-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'Pix'), ('pay_on_delivery', 'Pay on Delivery')], default='pay_on_delivery', max_length=20),
        ),
    ]
