# Generated by Django 5.1.2 on 2024-11-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="telegram_user_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
