# Generated by Django 5.1.2 on 2024-11-21 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_message_content_orderitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="client",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.client"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="message",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="message",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
